Work a bit harder at installing dummy libtool archives for machines that have binutils partially installed.
git-svn-id: http://svn.research.cc.gatech.edu/kaos/dill/trunk@3017 8ba6a8b9-845b-0410-94f0-974be2f5df47

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -880,6 +880,8 @@ CSH
 PATHPROG
 DUMMY_LIBOPCODES_TARGET
 LIBOPCODES_DIR
+INSTALL_DUMMY_OPCODES_TRUE
+INSTALL_DUMMY_OPCODES_FALSE
 MATH_LIB
 CONFIG_SIZEOF_LONG
 MULTI_TARGET_TRUE
@@ -5023,7 +5025,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5026 "configure"' > conftest.$ac_ext
+  echo '#line 5028 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7288,11 +7290,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7291: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7293: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7295: \$? = $ac_status" >&5
+   echo "$as_me:7297: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7578,11 +7580,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7581: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7583: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7585: \$? = $ac_status" >&5
+   echo "$as_me:7587: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7682,11 +7684,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7685: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7687: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7689: \$? = $ac_status" >&5
+   echo "$as_me:7691: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10031,7 +10033,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10034 "configure"
+#line 10036 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10131,7 +10133,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10134 "configure"
+#line 10136 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12551,11 +12553,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12554: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12556: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12558: \$? = $ac_status" >&5
+   echo "$as_me:12560: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12655,11 +12657,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12658: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12660: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12662: \$? = $ac_status" >&5
+   echo "$as_me:12664: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14217,11 +14219,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14220: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14222: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14224: \$? = $ac_status" >&5
+   echo "$as_me:14226: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14321,11 +14323,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14324: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14326: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14328: \$? = $ac_status" >&5
+   echo "$as_me:14330: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16508,11 +16510,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16511: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16513: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16515: \$? = $ac_status" >&5
+   echo "$as_me:16517: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16798,11 +16800,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16801: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16803: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16805: \$? = $ac_status" >&5
+   echo "$as_me:16807: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16902,11 +16904,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16905: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16907: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16909: \$? = $ac_status" >&5
+   echo "$as_me:16911: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19751,11 +19753,11 @@ fi
 
 search_list="$search_list /usr/include/dis-asm.h /usr/local/include/dis-asm.h /opt/binutils/include/dis-asm.h /opt/misc/include/dis-asm.h /opt/misc/include/$cercs_cv_archive/dis-asm.h"
 tmp_search_results=""
-echo "configure:19754: searching for $search_list " >&5
+echo "configure:19756: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:19758: first found $tmp_search_results " >&5
+	echo "configure:19760: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -19841,11 +19843,11 @@ fi
 
 search_list="$search_list /usr/lib/libopcodes.la /usr/local/lib/libopcodes.la /opt/binutils/lib/libopcodes.la /opt/misc/lib/libopcodes.la /opt/misc/lib/$cercs_cv_archive/libopcodes.la"
 tmp_search_results=""
-echo "configure:19844: searching for $search_list " >&5
+echo "configure:19846: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:19848: first found $tmp_search_results " >&5
+	echo "configure:19850: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -19965,11 +19967,11 @@ fi
 
 search_list="$search_list /usr/lib/libopcodes.a /usr/local/lib/libopcodes.a /opt/binutils/lib/libopcodes.a /opt/misc/lib/libopcodes.a /opt/misc/lib/$cercs_cv_archive/libopcodes.a"
 tmp_search_results=""
-echo "configure:19968: searching for $search_list " >&5
+echo "configure:19970: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:19972: first found $tmp_search_results " >&5
+	echo "configure:19974: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -20013,18 +20015,22 @@ fi
 
 if test x$cercs_cv_binutils_link_dir = x; then
   for tmp_lib_value in $sys_lib_search_path_spec; do
-     tmp=`ls $tmp_lib_value/libopcodes*.so`
+     tmp=`ls $tmp_lib_value/libopcodes*.so 2> /dev/null`
      if test "x$tmp" != "x"; then
-        cercs_cv_binutils_link_dir = $tmp_lib_value;
+        cercs_cv_binutils_link_dir=$tmp_lib_value;
      fi
   done
 fi
+if test "${cercs_cv_binutils_link_dir+set}" = set; then
 DUMMY_LIBOPCODES_TARGET=libopcodes.la
 LIBOPCODES_DIR=$cercs_cv_binutils_link_dir
 cercs_cv_binutils_link_dir=.
 cercs_cv_binutils_link_arg="-L."
 
 
+else
+NO_DISASSEMBLER="yes"
+fi
 fi
 else
 NO_DISASSEMBLER="yes"
@@ -20032,6 +20038,14 @@ fi
 if test x$kernel_build = xtrue; then
    NO_DISASSEMBLER="yes"
 fi
+ if test x$DUMMY_LIBOPCODES_TARGET != x; then
+  INSTALL_DUMMY_OPCODES_TRUE=
+  INSTALL_DUMMY_OPCODES_FALSE='#'
+else
+  INSTALL_DUMMY_OPCODES_TRUE='#'
+  INSTALL_DUMMY_OPCODES_FALSE=
+fi
+
 { echo "$as_me:$LINENO: checking for sqrt in -lm" >&5
 echo $ECHO_N "checking for sqrt in -lm... $ECHO_C" >&6; }
 if test "${ac_cv_lib_m_sqrt+set}" = set; then
@@ -20172,11 +20186,11 @@ fi
 
 search_list="$search_list /usr/include/avcall.h /usr/local/include/avcall.h /opt/ffcall/include/avcall.h /opt/misc/include/avcall.h /opt/misc/include/$cercs_cv_archive/avcall.h"
 tmp_search_results=""
-echo "configure:20175: searching for $search_list " >&5
+echo "configure:20189: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:20179: first found $tmp_search_results " >&5
+	echo "configure:20193: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -20262,11 +20276,11 @@ fi
 
 search_list="$search_list /usr/lib/libavcall.la /usr/local/lib/libavcall.la /opt/ffcall/lib/libavcall.la /opt/misc/lib/libavcall.la /opt/misc/lib/$cercs_cv_archive/libavcall.la"
 tmp_search_results=""
-echo "configure:20265: searching for $search_list " >&5
+echo "configure:20279: searching for $search_list " >&5
 for tmp_search_value in $search_list; do
    if test -r $tmp_search_value; then
 	tmp_search_results=$tmp_search_value
-	echo "configure:20269: first found $tmp_search_results " >&5
+	echo "configure:20283: first found $tmp_search_results " >&5
 	break
    fi
 done
@@ -23127,6 +23141,13 @@ echo "$as_me: error: conditional \"KERNEL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${INSTALL_DUMMY_OPCODES_TRUE}" && test -z "${INSTALL_DUMMY_OPCODES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"INSTALL_DUMMY_OPCODES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"INSTALL_DUMMY_OPCODES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${MULTI_TARGET_TRUE}" && test -z "${MULTI_TARGET_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"MULTI_TARGET\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -23836,6 +23857,8 @@ CSH!$CSH$ac_delim
 PATHPROG!$PATHPROG$ac_delim
 DUMMY_LIBOPCODES_TARGET!$DUMMY_LIBOPCODES_TARGET$ac_delim
 LIBOPCODES_DIR!$LIBOPCODES_DIR$ac_delim
+INSTALL_DUMMY_OPCODES_TRUE!$INSTALL_DUMMY_OPCODES_TRUE$ac_delim
+INSTALL_DUMMY_OPCODES_FALSE!$INSTALL_DUMMY_OPCODES_FALSE$ac_delim
 MATH_LIB!$MATH_LIB$ac_delim
 CONFIG_SIZEOF_LONG!$CONFIG_SIZEOF_LONG$ac_delim
 MULTI_TARGET_TRUE!$MULTI_TARGET_TRUE$ac_delim
@@ -23852,7 +23875,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 30; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 32; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
